"""Resolve and generate GUI report downloads.

This module is UI-only. It does not run BGP logic, does not compare snapshots,
and does not collect device data. It only exposes report files already generated
by the validated CLI workflow.
"""

from __future__ import annotations

import html
import json
import textwrap
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlencode

from maintenance_window.ui.executive_pdf import write_executive_pdf


@dataclass(frozen=True, slots=True)
class ReportDownload:
    path: Path
    content_type: str
    filename: str
    delete_after_send: bool = False


_VALID_KINDS = frozenset({"summary-txt", "detail-txt", "json", "pdf"})

_REPORT_FILES = {
    "summary-txt": ("full_summary.txt", "summary.txt"),
    "detail-txt": ("full_detail.txt", "detail.txt"),
    "json": ("full_report.json", "report.json"),
}

_CONTENT_TYPES = {
    "summary-txt": "text/plain; charset=utf-8",
    "detail-txt": "text/plain; charset=utf-8",
    "json": "application/json; charset=utf-8",
    "pdf": "application/pdf",
}

_LABELS = {
    "summary-txt": "Download Summary TXT",
    "detail-txt": "Download Detail TXT",
    "json": "Download JSON",
    "pdf": "Download PDF",
}


def _safe_filename(value: str) -> str:
    cleaned = "".join(
        char if char.isalnum() or char in {"-", "_", "."} else "_"
        for char in value
    )
    return cleaned.strip("._") or "report"


def _is_under_project(path: Path, project_root: Path) -> bool:
    try:
        path.resolve().relative_to(project_root.resolve())
        return True
    except ValueError:
        return False


def _mw_id_from_report_dir(report_dir: Path) -> str:
    # Expected: outputs/snapshots/bgp/<MW_ID>/comparison_reports/<timestamp>
    try:
        return report_dir.parents[1].name
    except IndexError:
        return "maintenance_window"


def _mw_id_from_export_path(export_path: Path) -> str:
    name = export_path.stem
    if name.startswith("gui_"):
        name = name[4:]
    for suffix in ("_full", "_state", "_session_health", "_session-health"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return name or "maintenance_window"


def _tmp_export_dir(project_root: Path) -> Path:
    del project_root  # kept for backward-compatible call signatures
    output_dir = (
        Path(tempfile.gettempdir())
        / "maintenance_window"
        / "gui_report_exports"
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def _resolve_existing_report_file(report_dir: Path, kind: str) -> Path:
    names = _REPORT_FILES.get(kind)
    if names is None:
        raise ValueError(f"Unsupported report export type: {kind}")

    for name in names:
        candidate = report_dir / name
        if candidate.exists() and candidate.is_file():
            return candidate

    expected = ", ".join(names)
    raise FileNotFoundError(
        f"No report file found for {kind}. Expected one of: {expected}"
    )


def _read_json_export(export_path: Path) -> dict[str, object]:
    data = json.loads(export_path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise ValueError("Export JSON must contain an object.")
    return data


def _get(data: dict[str, object], *keys: str) -> object:
    node: object = data
    for key in keys:
        if not isinstance(node, dict):
            return None
        node = node.get(key)
    return node


def _summary_text_from_json(export_path: Path) -> str:
    data = _read_json_export(export_path)
    lines = [
        "Maintenance Window Report Summary",
        "=================================",
        "",
        f"Source file: {export_path}",
        f"Overall result: {data.get('result') or _get(data, 'global_summary', 'overall_result')}",
        f"State result: {data.get('state_result') or _get(data, 'global_summary', 'modules', 'state')}",
        f"Session-health result: {data.get('session_health_result') or _get(data, 'global_summary', 'modules', 'session-health')}",
        f"Report directory: {data.get('report_directory') or 'N/A'}",
        "",
        "This text export was generated by the local GUI from the JSON report.",
    ]
    return "\n".join(lines) + "\n"


def _detail_text_from_json(export_path: Path) -> str:
    data = _read_json_export(export_path)
    return (
        "Maintenance Window Report Detail\n"
        "================================\n\n"
        f"Source file: {export_path}\n\n"
        + json.dumps(data, indent=2, sort_keys=True)
        + "\n"
    )


def _write_generated_text(
    project_root: Path,
    export_path: Path,
    kind: str,
    text: str,
) -> Path:
    output_dir = _tmp_export_dir(project_root)
    mw_id = _safe_filename(_mw_id_from_export_path(export_path))
    suffix = "summary.txt" if kind == "summary-txt" else "detail.txt"
    output_path = output_dir / f"{mw_id}_{time.time_ns()}_{suffix}"
    output_path.write_text(text, encoding="utf-8")
    return output_path


def _pdf_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def _content_stream_for_page(lines: list[str]) -> bytes:
    commands = ["BT", "/F1 10 Tf", "50 760 Td", "14 TL"]
    for line in lines:
        commands.append(f"({_pdf_escape(line)}) Tj")
        commands.append("T*")
    commands.append("ET")
    return "\n".join(commands).encode("latin-1", errors="replace")


def _build_simple_pdf(title: str, text: str) -> bytes:
    wrapped_lines: list[str] = []
    for raw_line in text.splitlines():
        if not raw_line.strip():
            wrapped_lines.append("")
            continue
        wrapped_lines.extend(textwrap.wrap(raw_line, width=92) or [""])

    lines = [title, ""] + wrapped_lines
    page_size = 52
    pages = [
        lines[index : index + page_size]
        for index in range(0, len(lines), page_size)
    ] or [[title]]

    font_obj = 3 + (len(pages) * 2)
    objects: dict[int, bytes] = {}
    kids: list[int] = []

    objects[1] = b"<< /Type /Catalog /Pages 2 0 R >>"

    for page_index, page_lines in enumerate(pages):
        page_obj = 3 + (page_index * 2)
        content_obj = page_obj + 1
        kids.append(page_obj)
        stream = _content_stream_for_page(page_lines)
        objects[page_obj] = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            f"/Resources << /Font << /F1 {font_obj} 0 R >> >> "
            f"/Contents {content_obj} 0 R >>"
        ).encode("ascii")
        objects[content_obj] = (
            f"<< /Length {len(stream)} >>\nstream\n".encode("ascii")
            + stream
            + b"\nendstream"
        )

    kids_refs = " ".join(f"{obj} 0 R" for obj in kids)
    objects[2] = (
        f"<< /Type /Pages /Kids [{kids_refs}] /Count {len(kids)} >>"
    ).encode("ascii")
    objects[font_obj] = b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"

    output = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for obj_num in sorted(objects):
        offsets.append(len(output))
        output.extend(f"{obj_num} 0 obj\n".encode("ascii"))
        output.extend(objects[obj_num])
        output.extend(b"\nendobj\n")

    xref_offset = len(output)
    max_obj = max(objects)
    output.extend(f"xref\n0 {max_obj + 1}\n".encode("ascii"))
    output.extend(b"0000000000 65535 f \n")
    for obj_num in range(1, max_obj + 1):
        obj_offset = offsets[obj_num] if obj_num < len(offsets) else 0
        output.extend(f"{obj_offset:010d} 00000 n \n".encode("ascii"))
    output.extend(
        f"trailer\n<< /Size {max_obj + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return bytes(output)


def _write_pdf_report_from_text(project_root: Path, mw_id: str, text: str) -> Path:
    output_dir = _tmp_export_dir(project_root)
    output_path = output_dir / f"{_safe_filename(mw_id)}_{time.time_ns()}_report.pdf"
    output_path.write_bytes(
        _build_simple_pdf(f"Maintenance Window Report - {mw_id}", text)
    )
    return output_path


def _write_pdf_report_from_dir(project_root: Path, report_dir: Path) -> Path:
    mw_id = _mw_id_from_report_dir(report_dir)

    for name in ("full_report.json", "report.json"):
        json_path = report_dir / name
        if not json_path.exists() or not json_path.is_file():
            continue
        try:
            data = _read_json_export(json_path)
        except (OSError, ValueError, json.JSONDecodeError):
            continue

        output_dir = _tmp_export_dir(project_root)
        output_path = output_dir / (
            f"{_safe_filename(mw_id)}_{time.time_ns()}_executive_report.pdf"
        )
        return write_executive_pdf(data, output_path)

    # Backwards-compatible fallback for older report directories that contain
    # only TXT artifacts.
    summary = ""
    detail = ""

    for name in ("full_summary.txt", "summary.txt"):
        path = report_dir / name
        if path.exists():
            summary = path.read_text(encoding="utf-8", errors="replace")
            break

    for name in ("full_detail.txt", "detail.txt"):
        path = report_dir / name
        if path.exists():
            detail = path.read_text(encoding="utf-8", errors="replace")
            break

    if not summary and not detail:
        raise FileNotFoundError(
            "No JSON or TXT report content found to generate PDF."
        )

    text = summary
    if detail:
        text = f"{summary}\n\nDETAIL\n======\n{detail}" if summary else detail

    return _write_pdf_report_from_text(project_root, mw_id, text)


def _resolve_from_report_dir(
    project_root: Path,
    report_dir: Path,
    kind: str,
) -> ReportDownload:
    mw_id = _safe_filename(_mw_id_from_report_dir(report_dir))

    if kind == "pdf":
        path = _write_pdf_report_from_dir(project_root, report_dir)
        return ReportDownload(
            path=path,
            content_type=_CONTENT_TYPES[kind],
            filename=f"{mw_id}_executive_report.pdf",
            delete_after_send=True,
        )

    path = _resolve_existing_report_file(report_dir, kind)
    suffix = {
        "summary-txt": "summary.txt",
        "detail-txt": "detail.txt",
        "json": "report.json",
    }[kind]
    return ReportDownload(
        path=path,
        content_type=_CONTENT_TYPES[kind],
        filename=f"{mw_id}_{suffix}",
    )


def _resolve_from_export_path(
    project_root: Path,
    export_path: Path,
    kind: str,
) -> ReportDownload:
    mw_id = _safe_filename(_mw_id_from_export_path(export_path))

    if kind == "json":
        return ReportDownload(
            path=export_path,
            content_type=_CONTENT_TYPES[kind],
            filename=f"{mw_id}_report.json",
        )

    if kind == "summary-txt":
        path = _write_generated_text(
            project_root,
            export_path,
            kind,
            _summary_text_from_json(export_path),
        )
        return ReportDownload(
            path=path,
            content_type=_CONTENT_TYPES[kind],
            filename=f"{mw_id}_summary.txt",
            delete_after_send=True,
        )

    if kind == "detail-txt":
        path = _write_generated_text(
            project_root,
            export_path,
            kind,
            _detail_text_from_json(export_path),
        )
        return ReportDownload(
            path=path,
            content_type=_CONTENT_TYPES[kind],
            filename=f"{mw_id}_detail.txt",
            delete_after_send=True,
        )

    if kind == "pdf":
        data = _read_json_export(export_path)
        output_dir = _tmp_export_dir(project_root)
        path = output_dir / (
            f"{_safe_filename(mw_id)}_{time.time_ns()}_executive_report.pdf"
        )
        write_executive_pdf(data, path)
        return ReportDownload(
            path=path,
            content_type=_CONTENT_TYPES[kind],
            filename=f"{mw_id}_executive_report.pdf",
            delete_after_send=True,
        )

    raise ValueError(f"Unsupported report export type: {kind}")


def _resolve_report_dir(project_root: Path, report_dir_text: str) -> Path:
    candidate = Path(report_dir_text).expanduser()
    if not candidate.is_absolute():
        candidate = project_root / candidate
    report_dir = candidate.resolve()
    allowed_root = (project_root / "outputs" / "snapshots" / "bgp").resolve()
    try:
        relative = report_dir.relative_to(allowed_root)
    except ValueError as exc:
        raise ValueError(
            "Report directory must be a BGP comparison report directory."
        ) from exc

    parts = relative.parts
    if len(parts) != 3 or parts[1] != "comparison_reports":
        raise ValueError(
            "Report directory must match "
            "outputs/snapshots/bgp/<MW_ID>/comparison_reports/<timestamp>."
        )
    if not report_dir.exists() or not report_dir.is_dir():
        raise FileNotFoundError(f"Report directory not found: {report_dir}")
    return report_dir


def _validate_gui_export_path(project_root: Path, export_path: Path) -> Path:
    allowed_root = (project_root / "outputs" / "reports").resolve()
    export_path = export_path.resolve()
    try:
        relative = export_path.relative_to(allowed_root)
    except ValueError as exc:
        raise ValueError(
            "GUI export must be inside outputs/reports."
        ) from exc

    if len(relative.parts) != 1:
        raise ValueError("GUI export must be a direct child of outputs/reports.")
    if export_path.suffix.lower() != ".json" or not export_path.name.startswith("gui_"):
        raise ValueError("GUI export must be a gui_*.json report file.")
    if not export_path.exists() or not export_path.is_file():
        raise FileNotFoundError(f"Export file not found: {export_path}")
    return export_path


def _resolve_export_path(project_root: Path, export_path_text: str) -> Path:
    export_path = Path(export_path_text).expanduser()
    if not export_path.is_absolute():
        export_path = project_root / export_path
    return _validate_gui_export_path(project_root, export_path)


def _resolve_export_file(project_root: Path, export_file_text: str) -> Path:
    filename = Path(export_file_text).name
    if not filename:
        raise ValueError("Missing export file name.")
    export_path = project_root / "outputs" / "reports" / filename
    return _validate_gui_export_path(project_root, export_path)


def resolve_report_download(
    project_root: Path,
    report_dir_text: str = "",
    kind: str = "",
    export_path_text: str = "",
    export_file_text: str = "",
) -> ReportDownload:
    """Resolve a report download request into a local file attachment.

    Priority:
    1. report_dir_text for full comparison artifacts.
    2. export_file_text for GUI JSON exports under outputs/reports.
    3. export_path_text for backwards compatibility and tests.
    """
    if kind not in _VALID_KINDS:
        raise ValueError(f"Unsupported report export type: {kind}")

    project_root = project_root.resolve()

    if report_dir_text.strip():
        try:
            report_dir = _resolve_report_dir(project_root, report_dir_text)
            return _resolve_from_report_dir(project_root, report_dir, kind)
        except FileNotFoundError:
            if not export_file_text.strip() and not export_path_text.strip():
                raise

    if export_file_text.strip():
        export_path = _resolve_export_file(project_root, export_file_text)
        return _resolve_from_export_path(project_root, export_path, kind)

    if export_path_text.strip():
        export_path = _resolve_export_path(project_root, export_path_text)
        return _resolve_from_export_path(project_root, export_path, kind)

    raise ValueError("Missing report directory or export reference.")


def build_export_actions(report_summary: dict[str, object] | None) -> str:
    """Build result-page download buttons.

    Full reports normally expose a report directory. State/session-health reports
    normally expose only the GUI JSON export path. For JSON exports, the rendered
    URL carries only the filename and the server resolves it inside outputs/reports.
    """
    if not report_summary:
        return ""

    report_dir = report_summary.get("report_directory")
    export_path = report_summary.get("export_path")

    has_report_dir = isinstance(report_dir, str) and bool(report_dir.strip())
    has_export_path = isinstance(export_path, str) and bool(export_path.strip())

    if not has_report_dir and not has_export_path:
        return ""

    links: list[str] = []
    for kind in ("summary-txt", "detail-txt", "json", "pdf"):
        query_data = {"kind": kind}
        if has_report_dir:
            query_data["report_dir"] = str(report_dir)
        if has_export_path:
            query_data["export_file"] = Path(str(export_path)).name

        query = urlencode(query_data)
        links.append(
            '<a class="button-link secondary export-button" '
            f'href="/download-report?{html.escape(query, quote=True)}">'
            f"{html.escape(_LABELS[kind])}</a>"
        )

    return (
        '<div class="export-actions">'
        '<h3>Export reports</h3>'
        '<p class="muted">Download full technical evidence or the executive PDF view.</p>'
        '<div class="export-button-row">'
        + "\n".join(links)
        + "</div></div>"
    )
